### ISSUE TITLE
Allowing to preserve position of comments

### ISSUE THREAD

**Issue by renehamburger** [SoominHan/import-sorter#14]
There are several reasons why one might want to preserve the position of comments:
1. Wanting to keep a comment about the current file or a triple slash directive at the very top of the file.
2. Needing to disable a tslint-rule for a black-listed import, i.e. `// tslint:disable-next-line:import-blacklist`.
3. Wanting to comment on an import, especially when it is a side-effect import.

Keeping line comments in the correct place would be quite tricky, as the following import statement might not only be moved but merged with another one. But for now, keeping any comments that are above the import block up there would solve (1) and provide a workaround for (2) (as it allows to use `// tslint:disable:import-blacklist`).

What are your thoughts on this, @SoominHan?

**Comment by renehamburger** [comment]
Another temporary workaround would be to not change the import block at all if all import statements are in the right place. That way the comment(s) would still be moved down when the import block is sorted initially, but could then be moved back to the right place.
Would you be interested in a PR implementing this?

**Comment by mike-co** [comment]
Preserving the position of the comments is on my roadmap of things to do when i get some free time. 
I would rather go for the proper solution though. That is to use typescript compiler api to get positions of all commens which have an associated to it import. Then we just need to extend internal models to include those. Once that one is done, it will be easy to arrange comments properly. So, PR in that direction will be acceptable.

**Comment by renehamburger** [comment]
Thanks, that would be great! I'll disable the import sorting in those files for the time being.

**Comment by mike-co** [comment]
Sure. I will try to get things working sometime next week.

**Comment by mike-co** [comment]
Done in 2.0.1

**Comment by renehamburger** [comment]
Fantastic! Works like a charm!
