### ISSUE TITLE
prevent sorting of side-effect imports

### ISSUE THREAD

**Issue by phryneas** [SoominHan/import-sorter#15]
Hi there, thanks for the great tool :)

I would love to see an option to prevent auto-sorting of imports with side effects.

For example, the following two statements have completely different effects:

```
import 'normalize.css/normalize.css';
import '@blueprintjs/core/lib/css/blueprint.css';
import '@blueprintjs/icons/lib/css/blueprint-icons.css';
```

```
import '@blueprintjs/core/lib/css/blueprint.css';
import '@blueprintjs/icons/lib/css/blueprint-icons.css';
import 'normalize.css/normalize.css';
```

in this specific case, those are css imports - but it might also be the case that a javascript file with side effects relies on side effects from another javascript import that should have been imported before.

So it would be great to keep the generic sorting behaviour for everything else, but only group side-effect imports without sorting them.

Is that possible?

**Comment by mike-co** [comment]
Hi. Currently it is not supported. I will need to add an option of skiping sorting for the group. I will include it into the next release. Therefore you will be able to turn of sorting for any regular expression group. Though it will be up to you to set the actual group. That is the group of side effect imports.

**Comment by mike-co** [comment]
Added in the 2.0.1 release. 
You will need to add `disableSort: true` flag in the `importSorter.sortConfiguration.customOrderingRules.rules`. For example the following config should work for your specific case: 
```json
[
    {
        "type": "importMember",
        "regex": "^$",
        "orderLevel": 10,
        "disableSort": true
    },
    {
        "regex": "^[@]",
        "orderLevel": 30
    },
    {
        "regex": "^[.]",
        "orderLevel": 40
    }
]
```

**Comment by phryneas** [comment]
cool, will test this tomorrow. thank you!

**Comment by phryneas** [comment]
sorry, I forgot to report back. this works like a charm. thank you very much!
