### ISSUE TITLE
Add some cli method to sort imports of all typescript files in project directory

### ISSUE THREAD

**Issue by krystofcelba** [SoominHan/import-sorter#17]
Hi,
thanks for this great extension! (although I'm now affected by #16 :/ )
I think that it would be definitely great to add some method to run sorting of imports on all *.ts(x) files in project dir. The use case is for example when you start using this extension in the mid of project and want to standardize all files in batch.

Thanks!

**Comment by mike-co** [comment]
Sure. Will place on a backlog and will try to implement this once I have a bit of free time.

**Comment by mike-co** [comment]
Took a while to get back to the project. The feature is added in v3.0.0
![import-sorter-example-2](https://user-images.githubusercontent.com/12505866/47717652-3d412d00-dcab-11e8-93c3-b5dd3116d252.gif)
