### ISSUE TITLE
trailing commas

### ISSUE THREAD

**Issue by Plondrein** [SoominHan/import-sorter#2]
When line is too long, it is automatically cut and it's great but is it possible to add also trailing commas?

**Comment by mike-co** [comment]
Would you be able to provide an example here. Particularly what you have before sorting, and what result you would expect to have after ?

**Comment by Plondrein** [comment]
Sorry i had to use external site, code pasted here doesn't show what i mean.

i got: https://bpaste.net/show/b8fb4da16615
After i perform 'Sort Imports' it becomes https://bpaste.net/show/0efd695eca13

and leaves missing comma at the end of the line.
I'd love to have it automatically appended.

**Comment by mike-co** [comment]
Correct me if I am wrong:
Given: 
```ts
import { Component, Input, OnChanges, ChangeDetectionStrategy, SimpleChanges, OnDestroy, Output, DebugElement } from '@angular/core';
```
The output after sorting with `"importSorter.importStringConfiguration.maximumNumberOfImportExpressionsPerLine.count": 105:`
and
`"importSorter.importStringConfiguration.tabSize": 4,`
is
```ts
import {
    ChangeDetectionStrategy, Component, DebugElement, Input, OnChanges, OnDestroy, Output, SimpleChanges
} from '@angular/core';
```
and you would expect to have the following
```ts
import {
    ChangeDetectionStrategy, Component, DebugElement, Input, OnChanges, OnDestroy, Output, SimpleChanges,
} from '@angular/core';
```
which would add an extra comma at the end. Sure it can be done. I will call a new setting as `importSorter.importStringConfiguration.hasMultiLineTrailingComma` with the default being false. I will try to add this somehow this week.

**Comment by Plondrein** [comment]
Exactly! It would be super cool to see this live :)

**Comment by mike-co** [comment]
Added `importSorter.importStringConfiguration.trailingComma` setting. This setting can have `always`, `multiLine`, or `none` values. If you need a trailing comma only for multiple lines then use `multiLine`, otherwise you can use `always`. I have also added reading settings from the file so that it can be shared between a team and committed to the source control if needed. See read-me for this, if interested.

**Comment by Plondrein** [comment]
that's great to hear! Will it be possible to update import-sorter directly from vs code?

**Comment by mike-co** [comment]
That is definitely possible. I have already bumped the version of the plugin. Depending on version of vscode, you should be able to open installed extensions and press update (if it is not done automatically). The plugin page is https://marketplace.visualstudio.com/items?itemName=mike-co.import-sorter.

**Comment by Plondrein** [comment]
I got it! It works just as i dreamed! Thanks 👍
