### ISSUE TITLE
how can i sort this path after my declares

### ISSUE THREAD

**Issue by EternalChildren** [SoominHan/import-sorter#24]
i like to add some declares above code in file
e.g 
`// style`
`// created by XXX on 2018/11/29`
`"use strict"`
when i use the command to sort import, then import will move to place where above declare.
e.g
`import xx from "xx"`
`// style`
`// created by`
but in my mind , the true style is like this
`// style`
`// created by`
`"use strict"`
`import xx from "xx"`
so  can i get the func with the plugin or what i need to do ?

forgive my worst english :) thanks

**Comment by EternalChildren** [comment]
I realized it caused by 'use strict'
so the better way is recognize 'use strict' and divid it into comment

**Comment by mike-co** [comment]
should be fixed in v3.3.1
