### ISSUE TITLE
Sorting similar to TypeScript "editor.organizeImports"

### ISSUE THREAD

**Issue by devlfm** [SoominHan/import-sorter#30]
Hi,

Great extension! I'm struggling to find the setting that match sorting between import-sorter and typescript organize-imports.
I'm using both because "organize-imports" removes unused imports, and "import-sorter" respects max-line-length for tslint rule. And I just wanna to match the sorting settings, because I have a "onSaveAction" and everytime I save a file, it will re-sort the imports sorted by "organize-imports" and sometimes there's no reason..
I believe it have something to do with imports with "@" prefix:

"editor.organizeImports":
> import { Component, QueryList, ViewChildren } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import * as Application from 'application';
import { RouterExtensions } from 'nativescript-angular';
import { orientationCleanup, setCurrentOrientation } from 'nativescript-screen-orientation';
import { forkJoin, of } from 'rxjs';
import { catchError, tap } from 'rxjs/operators';
import { screen } from 'tns-core-modules/platform';

"import-sorter":
> import * as Application from 'application';
import { RouterExtensions } from 'nativescript-angular';
import { orientationCleanup, setCurrentOrientation } from 'nativescript-screen-orientation';
import { forkJoin, of } from 'rxjs';
import { catchError, tap } from 'rxjs/operators';
import { screen } from 'tns-core-modules/platform';
import { Component, QueryList, ViewChildren } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

Hope you can help me!
Thank you

**Comment by mike-co** [comment]
If you use the following configuration it should give the same result. Basically we want to place all of the @ imports at the bottom of the list. That can be achieved by updating default rules for ordering.
``` json
  "importSorter.sortConfiguration.customOrderingRules.rules": [
    {
      "type": "importMember",
      "regex": "^$",
      "orderLevel": 5,
      "disableSort": true
    },
    {
      "regex": "^[.]",
      "orderLevel": 30
    },
    {
      "regex": "^[@]",
      "orderLevel": 50
    }
],
"importSorter.sortConfiguration.customOrderingRules.defaultNumberOfEmptyLinesAfterGroup": 0
```
Using regex and orderLevel, you should be able to achieve a variety of combinations.

I did add the feature of removing the duplicates as well. You could also consider using it instead:
```json
"importSorter.sortConfiguration.removeUnusedImports": true
```
