### ISSUE TITLE
#!/ gets moved from top of file

### ISSUE THREAD

**Issue by Lightw3ight** [SoominHan/import-sorter#39]
In the public_api to my library at the very top, I have the following line
```
#!/usr/bin/env node
```

When I use this extension, it moves this line below the imports which breaks the file

Before save
```
#!/usr/bin/env node
import { run } from './lib/index';
```

After Save
```
import { run } from './lib/index';

#!/usr/bin/env node
```

**Comment by mike-co** [comment]
Should be fixed in v3.3.1
