### ISSUE TITLE
Add support for .tsx(typescriptreact)

### ISSUE THREAD

**Issue by varHarrie** [SoominHan/import-sorter#4]
https://github.com/SoominHan/import-sorter/blob/d2d81d064f0a16cb68fbdefa7e5ba8ac95ab6557/src/import-sorter-extension.ts#L157

From a grammar point of view, they are almost identical. It should be compatible and we can only change the `languageId`.

BTW, This extension is the best one for import sorting  I used, and if there is a logo in [vscode marketplace](https://marketplace.visualstudio.com/items?itemName=mike-co.import-sorter), it will let more people know.

**Comment by mike-co** [comment]
Glad that you liked it. Updated the code and bumped the version of the extension. Would you be able to open a different issue for the logo. I will try to find some time this week to polish my drawing skills :)

**Comment by mike-co** [comment]
Took a while, but created an icon in the latest version.
