### ISSUE TITLE
How to setup extension for dividing modules and others imports in two groups, spacing by empty string, sorting by string?

### ISSUE THREAD

**Issue by Depact** [SoominHan/import-sorter#40]
I searching extension that allows me sort imports like this:
> import { Actions } from '@ngxs/store';
import { Component } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { Router } from '@angular/router';
import { Subscription } from 'rxjs';
> 
> import { CreateUser, UpdateUser, SetUser } from '../../../store/user/user.actions';
import { UserState } from '../../../store/user/user.state';
>
> @Component({

TypeScript Hero do almost the same, but sorts modules by package name. I need only simple alphabet sorting for imports strings. And TypeScript Hero abandoned.

**Comment by mike-co** [comment]
you can set this order quite easy by using regular expressions. As far as settings update goes, you will just need to update rules. However, you example here is not strictly an alphabetical order, due to @ngxs/store (presumably @ngrx/store) is before @angular, which is `n` before `a`.
It is still can be achieved with the following configuration
```json
  "importSorter.sortConfiguration.customOrderingRules.rules": [
    {
      "regex": "^[@]ngxs",
      "orderLevel": 10,
      "numberOfEmptyLinesAfterGroup": 0
    },
    {
      "regex": "^[.]",
      "orderLevel": 30
    }
],
```
alternatively, if you meant to place everything in alphabetical order, and wanted `a` and then `n`, you can use
```json
  "importSorter.sortConfiguration.customOrderingRules.rules": [
    {
      "regex": "^[.]",
      "orderLevel": 30
    }
],
```

**Comment by DeltaImpact** [comment]
> you example here is not strictly an alphabetical order


I searching extension that allows me sort imports like this:
> **import { A**ctions } from '@ngxs/store';
**import { C**omponent } from '@angular/core';
**import { F**ormGroup } from '@angular/forms';
**import { R**outer } from '@angular/router';
**import { S**ubscription } from 'rxjs';

**A** B **C** D E **F** G H I J K L M N O P Q **R** **S** T U V W X Y Z

> **import { C**reateUser, UpdateUser, SetUser } from '../../../store/user/user.actions';
**import { U**serState } from '../../../store/user/user.state';

A B **C** D E F G H I J K L M N O P Q R S T **U** V W X Y Z

But it's in alphabetical order, sorting by string.

**Comment by mike-co** [comment]
So you do not want to sort by import paths ?

**Comment by DeltaImpact** [comment]
Yes. I used bold to highlight, that I need sorting by full string.

**Comment by mike-co** [comment]
try the following:
```json
  "importSorter.sortConfiguration.customOrderingRules.rules": [
    {
      "type": "importMember",
      "regex": "^.?$",
      "orderLevel": 0,
      "disableSort": false
    }
  ],
  "importSorter.sortConfiguration.customOrderingRules.defaultOrderLevel": 0
```

**Comment by DeltaImpact** [comment]
**import { C**omponent } from '@angular/core';
**import { F**ormGroup } from '@angular/forms';
**import { R**outer } from '@angular/router';
**import { A**ctions } from '@ngxs/store';
**import { S**ubscription } from 'rxjs';
**import { C**reateUser, SetUser, UpdateUser } from '../../../store/user/user.actions';
**import { U**serState } from '../../../store/user/user.state';

Letter C before A. Not divides in two groups.

**Comment by mike-co** [comment]
I think I understand now what you are trying to do. Basically you want to group by paths first. Then inside of the group you want to sort import members by their import name. Then you want to order the imports in the group by first sorted import name.

Hmm. Currently this behavior is not supported by the plugin. I could place it on a backlog of features to implement, but it will need to wait till some of the bugs I place priority in are fixed. 

Any reason why you do not want to sort by the import paths ? The personal preference is also a valid reason, but if it is something else I would like to know about it?

**Comment by DeltaImpact** [comment]
Style guide of projects I work with. No idea, why such moment applied. But I work with it.

**Comment by lonix1** [comment]
I think the issue is not the sort order, bur that he wants to have platform imports first, and then project imports. We do the same here, as do many projects.

So angular, rxjs, etc. will be sorted in one group. And the project's internal stuff sorted in another group.

The best option is to be able to define a regex with "platform" paths, e.g. `/[angular|rxjs|ngrx]/` and that goes into the first group. EVerything else goes into the second group.

Can this be done somehow?

**Comment by tomasloksa** [comment]
I would also love this feature. Sorting by import names inside groups would be great.

I might even look into it myself, when i'll have some free time

**Comment by daidodo** [comment]
Has this issue been resolved? If not, I'd like to recommend [this extension](https://marketplace.visualstudio.com/items?itemName=dozerg.tsimportsorter) which may help:

```json
{
  "sortImportsBy": "names",
  "groupRules": ["angular|rxjs|ngrx"]
}
```

The above rules will put imports from `angular`, `rxjs` and `ngrx` in the first group, and all others in the (second) fall-back group.

You can further tune other aspects such as empty lines between groups, case-(in)sensitivity when comparing binding names or paths, or even different sorting rules for different groups.
