### ISSUE TITLE
removeUnusedImports removes React import

### ISSUE THREAD

**Issue by stigi** [SoominHan/import-sorter#41]
Hi,

Thanks for import-sorter, it's awesome! I especially love the configurability.

I'm running into issues with SFCs though, where the `import React from 'react'` import that is needed for JSX will be cleaned up when `removeUnusedImports` is set.

Here's an example:

```
import React from 'react'
import { Text, ViewProperties } from 'react-native'

export default ({ style }: ViewProperties) => (
  <Text style={style}>Ohai!</Text>
)
```

Any idea if it's currently possible work around this?

Thanks! Again 😆 !

**Comment by fstojanac** [comment]
Faced the same problem, [#42](https://github.com/SoominHan/import-sorter/pull/42) should solve this issue.

**Comment by mike-co** [comment]
I will probably go with the approach of treating default imports as imports with side effects (as they can be). This will cover the majority of the use-cases, including your one.

**Comment by mike-co** [comment]
Should be fixed in v3.3.1

**Comment by fstojanac** [comment]
Great, works for me!

**Comment by luke-robertson** [comment]
@mike-co dosnt work for `import * as React from 'react';` any suggestions ?
