### ISSUE TITLE
Option to not normalize `.` and `..`

### ISSUE THREAD

**Issue by evankennedy** [SoominHan/import-sorter#48]
Using ESLint [`import/no-useless-path-segments`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-useless-path-segments.md), having a paths of `./` or `../` will cause linting errors. I can see why some people would prefer having that path separator so I'm not requesting a change, but an option to remove this.

**Comment by daidodo** [comment]
Could you provide code examples about this issue?

**Comment by daidodo** [comment]
Actually, this rule is NOT going to work in all cases. For example:

```
my-project
├── helpers.js
└── helpers
    ├── contact.js
    └── index.js      // Export {AAA}
```

In *contact.js*:

```js
import {AAA} from '.';  // ts(2305): Module '"my-project/helpers"' has no exported member 'AAA'.
```

You have to use `import {AAA} from './'` to avoid the compiler error.

Similar cases to `'..'`, too.

**Comment by evankennedy** [comment]
Wow, today I learned something new about the javascript import system. Thank you for giving me a better understanding! Going to close this issue.

**Comment by JordanLongstaff** [comment]
Hi @daidodo, I've received a complaint from a coworker about this behaviour. He and I have both read this discussion, and here's what he said:
```
OK so I see daidodo's argument but their example is an antipattern. We should never have both a file and a folder with the same name in the same directory

'helpers.js' in their example should have its code moved into 'helpers/index.js', by our code conventions anyway
```
