### ISSUE TITLE
Control of single import to new line?

### ISSUE THREAD

**Issue by abogartz** [SoominHan/import-sorter#5]
Great plugin! I'm running into an issue with another formatter fighting with the styles here. [Prettier](https://github.com/prettier/prettier) attempts to format lines, but does something like this:

`import { A } from './a';`

Will be formatted to a single line, while something this:

```
import {
 ALongClass,
 AnotherLongClassName
} from './a';
```

...will wrap based on the width of the line. What I'd like to do is have import-sorter work in the same way: if the total width is less than some number, put the whole thing on one line, otherwise put each import on its own line. I've been playing around with the config but haven't been able to figure it out.

**Comment by abogartz** [comment]
I think it would be a good thing to be able to control. I'll take a closer look at your code and see if I can get that working. If so, I'll open a PR. Thanks!

**Comment by mike-co** [comment]
Hmm. Took a while for me to come back to this project. 

I have done your request in the latest version. You will need to set `importSorter.importStringConfiguration.maximumNumberOfImportExpressionsPerLine.type`: `newLineEachExpressionAfterCountLimit` 

and 

`importSorter.importStringConfiguration.maximumNumberOfImportExpressionsPerLine.count`: `Some number value`. 

Therefore, `count` would denote maximum number of characters which can be on the first line. If all imports do not fit one line, then each import will be placed on a new line.
