### ISSUE TITLE
Option for choosing between space or tab

### ISSUE THREAD

**Issue by AAudusseau** [SoominHan/import-sorter#6]
Hi, thanks for the plugin it's very useful.
In my projects I use tabs for indentation, and I didn't see an option to choose between tabs or spaces for new lined imports. Is there a way to do that ? And if not, is it possible to add an option to do that ?

**Comment by mike-co** [comment]
Sure, would be possible to add. Currently I am travelling though, but should be back in the end of the week. After that I will try to go through unresolved issues, including this.

**Comment by mike-co** [comment]
Created importSorter.importStringConfiguration.tabType configuration option. You will need to set it to 'tab', as default one is 'space'. Currently you will still need to specify the size of the spaces the tab is using. That is done by setting a number of spaces for the tab in importSorter.importStringConfiguration.tabSize.

**Comment by AAudusseau** [comment]
Thanks a lot !
