### ISSUE TITLE
Sort on save

### ISSUE THREAD

**Issue by calvinrempel** [SoominHan/import-sorter#7]
This is a great extension, it's the only one I've found that lets me easily configure the sorting rules just as I want them. But, it would be even better if it had an option to sort imports when a file is saved.

Please consider adding this feature. Thanks!

**Comment by mike-co** [comment]
Sure. Will do it in the next feature

**Comment by calvinrempel** [comment]
Awesome, thanks!

**Comment by mike-co** [comment]
done in v1.1.1. You will need to enable importSorter.generalConfiguration.sortOnBeforeSave setting to true.
