### ISSUE TITLE
Add option to ignore files

### ISSUE THREAD

**Issue by pfeigl** [SoominHan/import-sorter#9]
Please add an option to ignore certain files. List of regex would be nice.

Popular example is "polyfill.ts" in any angular project, because this file contains alot of comments and "areas" in which the default imports are sorted into.

Thanks :)
Philipp

**Comment by mike-co** [comment]
Sure. I will try to find some time at the end of this week to implement the feature.

**Comment by mike-co** [comment]
Sorry for a delay. I have added the feature. The example of usage:
```json
    {
      "generalConfiguration": {
        "exclude": [
          ".*polyfill\\.ts"
        ]
      }
    }
```
